/* Things the mirror can say: jokes, facts, riddles, compliments, pep talks. */
M.content = {
  jokes: [
    'Why did the mirror go to school? To reflect on its lessons.',
    'Why don\'t skeletons fight each other? They don\'t have the guts.',
    'What do you call a fake noodle? An impasta.',
    'Why did the scarecrow win an award? Because he was outstanding in his field.',
    'What do you call a bear with no teeth? A gummy bear.',
    'Why can\'t a bicycle stand up by itself? It\'s two tired.',
    'What do you call cheese that isn\'t yours? Nacho cheese.',
    'Why did the math book look sad? It had too many problems.',
    'What did the ocean say to the beach? Nothing, it just waved.',
    'How do you organise a space party? You planet.',
    'Why was the computer cold? It left its Windows open.',
    'What do you call a sleeping dinosaur? A dino-snore.',
    'Why did the cookie go to the doctor? It felt crummy.',
    'What has ears but cannot hear? A cornfield.',
    'Why do bees have sticky hair? Because they use honeycombs.',
    'What did one wall say to the other? I\'ll meet you at the corner.',
    'Why did the golfer bring two pairs of trousers? In case he got a hole in one.',
    'What do you call a dog magician? A labracadabrador.',
    'Why are elevator jokes so good? They work on many levels.',
    'What do you get when you cross a snowman and a vampire? Frostbite.',
    'Why did the student eat their homework? The teacher said it was a piece of cake.',
    'What kind of tree fits in your hand? A palm tree.',
    'Why don\'t eggs tell jokes? They\'d crack each other up.',
    'What do you call a pile of cats? A meowntain.',
    'Why did the phone wear glasses? It lost its contacts.',
    'What did the left eye say to the right eye? Between you and me, something smells.',
    'Why was the broom late? It over-swept.',
    'What\'s orange and sounds like a parrot? A carrot.',
    'Why did the banana go to the doctor? It wasn\'t peeling well.',
    'How does the moon cut its hair? Eclipse it.',
    'What do you call an alligator in a vest? An investigator.',
    'Why did the light bulb fail school? It wasn\'t very bright. Unlike you.',
    'What do clouds wear under their clothes? Thunderwear.',
    'Why did the music teacher need a ladder? To reach the high notes.',
    'What did the Wi-Fi say to the mirror? I feel a real connection.'
  ],
  facts: [
    'Honey never spoils. Archaeologists have found pots of honey in ancient Egyptian tombs that are still edible.',
    'Octopuses have three hearts and blue blood.',
    'A day on Venus is longer than a year on Venus.',
    'Bananas are berries, but strawberries are not.',
    'Your brain uses about 20 percent of your body\'s energy.',
    'Sharks existed before trees.',
    'There are more stars in the universe than grains of sand on all of Earth\'s beaches.',
    'A group of flamingos is called a flamboyance.',
    'Sloths can hold their breath longer than dolphins, up to 40 minutes.',
    'The Eiffel Tower can be about 15 centimetres taller in summer because metal expands in heat.',
    'Butterflies taste with their feet.',
    'Cows have best friends and get stressed when they are apart.',
    'An ostrich\'s eye is bigger than its brain.',
    'Hot water can freeze faster than cold water in some conditions. It\'s called the Mpemba effect.',
    'The heart of a blue whale is about the size of a small car.',
    'Wombat poop is cube-shaped.',
    'Light from the Sun takes about 8 minutes to reach Earth.',
    'Your fingernails grow faster on your dominant hand.',
    'Sea otters hold hands while they sleep so they don\'t drift apart.',
    'A bolt of lightning is about five times hotter than the surface of the Sun.',
    'Mirrors work because a thin metal layer behind the glass reflects light. Your smart mirror uses the same idea with film.',
    'Two-way mirrors only work when one side is brighter than the other. That\'s how this mirror shows the screen.',
    'Peacocks are not the only ones with fancy feathers. Male birds of paradise dance to impress.',
    'Rainbows are actually full circles. We usually only see half because the ground is in the way.',
    'Koalas sleep up to 22 hours a day.',
    'Saturn would float in a bathtub big enough, because it is less dense than water.',
    'Some turtles can breathe through their bottoms.',
    'The Great Wall of China is not visible from space with the naked eye.',
    'Humans share about 60 percent of their DNA with bananas.',
    'The ESP32 inside this mirror can run at 240 million steps a second.',
    'Chess has more possible games than there are atoms in the observable universe.',
    'Goldfish can remember things for months, not just three seconds.',
    'Penguins propose to each other with pebbles.',
    'India has the world\'s highest cricket ground, in Chail, Himachal Pradesh.',
    'The Indian national game is often thought to be hockey, but India has no official national game.'
  ],
  riddles: [
    ['What has to be broken before you can use it?', 'An egg.'],
    ['I\'m tall when I\'m young and short when I\'m old. What am I?', 'A candle.'],
    ['What has hands but can\'t clap?', 'A clock.'],
    ['What gets wetter the more it dries?', 'A towel.'],
    ['What has keys but can\'t open locks?', 'A piano.'],
    ['What can you catch but not throw?', 'A cold.'],
    ['What has one eye but can\'t see?', 'A needle.'],
    ['What goes up but never comes down?', 'Your age.'],
    ['What has many teeth but can\'t bite?', 'A comb.'],
    ['The more you take, the more you leave behind. What are they?', 'Footsteps.'],
    ['What can travel around the world while staying in a corner?', 'A stamp.'],
    ['What shows your face but has no face of its own?', 'A mirror. Hi.'],
    ['What has a neck but no head?', 'A bottle.'],
    ['What is full of holes but still holds water?', 'A sponge.'],
    ['What runs but never walks?', 'Water.']
  ],
  compliments: [
    'You look ready to take on the day.',
    'Honestly, your reflection looks great today.',
    'You built a smart mirror. That is seriously impressive.',
    'You have great taste. You picked me, after all.',
    'Your smile could power my LED strip.',
    'You\'re smarter than you think.',
    'That outfit works.',
    'You\'re the main character today.',
    'Whatever you\'re planning, you\'ve got this.',
    'You make this mirror look good.',
    'Your ideas are brilliant. I\'m literally proof.',
    'Kind people are the coolest people, and you\'re one of them.'
  ],
  pep: [
    'Small steps still move you forward.',
    'You don\'t have to be perfect, just keep going.',
    'Mistakes are proof that you\'re trying.',
    'Start with five minutes. Future you will be grateful.',
    'You\'ve handled hard days before. You can handle this one.',
    'Done is better than perfect.',
    'Drink some water, take a breath, then start.',
    'Every expert was once a beginner.',
    'Believe you can, and you\'re halfway there.',
    'Focus on progress, not perfection.',
    'One task at a time. You\'ve got this.',
    'Today is a good day to be proud of yourself.'
  ],
  eightBall: ['Yes, definitely.', 'It is certain.', 'Most likely.', 'Ask again later.', 'Better not tell you now.', 'Don\'t count on it.', 'My reply is no.', 'Signs point to yes.', 'Very doubtful.', 'Without a doubt.', 'Concentrate and ask again.', 'Outlook good.']
};
